"""Initial schema with all entities

Revision ID: ff3c38739220
Revises: 
Create Date: 2025-12-20 20:37:40.040812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff3c38739220'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committees',
    sa.Column('committee_id', sa.String(length=50), nullable=False, comment='Unique identifier for the committee'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Committee name'),
    sa.Column('purpose', sa.Text(), nullable=True, comment='Purpose and responsibilities of the committee'),
    sa.Column('meeting_frequency', sa.String(length=100), nullable=True, comment="How often the committee meets (e.g., 'weekly', 'as-needed')"),
    sa.Column('chair_id', sa.UUID(), nullable=True, comment='ID of the committee chair'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chair_id'], ['agent_desks.id'], name='fk_committee_chair', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committees_committee_id'), 'committees', ['committee_id'], unique=True)
    op.create_index(op.f('ix_committees_created_at'), 'committees', ['created_at'], unique=False)
    op.create_index(op.f('ix_committees_deleted_at'), 'committees', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_committees_id'), 'committees', ['id'], unique=False)
    op.create_table('metrics',
    sa.Column('metric_id', sa.String(length=50), nullable=False, comment="Identifier for the metric (e.g., 'task_completion_rate')"),
    sa.Column('metric_name', sa.String(length=200), nullable=False, comment='Human-readable metric name'),
    sa.Column('metric_type', sa.String(length=50), nullable=False, comment='Type of metric (counter, gauge, histogram, etc.)'),
    sa.Column('value_float', sa.Float(), nullable=True, comment='Numeric value for the metric'),
    sa.Column('value_int', sa.Integer(), nullable=True, comment='Integer value for the metric'),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Dimensions/tags for grouping (e.g., desk_id, team_id)'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional metric metadata'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_created_at'), 'metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_metric_id'), 'metrics', ['metric_id'], unique=False)
    op.create_index(op.f('ix_metrics_metric_type'), 'metrics', ['metric_type'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=50), nullable=False, comment='Unique identifier for the notification'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='Type of event that triggered this notification'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Notification title'),
    sa.Column('message', sa.Text(), nullable=False, comment='Notification message content'),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Channels to send notification to (slack, email, etc.)'),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of recipients (desk IDs, email addresses, etc.)'),
    sa.Column('sent', sa.Boolean(), nullable=False, comment='Whether the notification has been sent'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional notification metadata'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_event_type'), 'notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=True)
    op.create_index(op.f('ix_notifications_sent'), 'notifications', ['sent'], unique=False)
    op.create_table('organizations',
    sa.Column('org_name', sa.String(length=200), nullable=False, comment='Organization name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Organization description'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Organization-wide configuration settings'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional organization metadata'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_org_name'), 'organizations', ['org_name'], unique=True)
    op.create_table('teams',
    sa.Column('team_id', sa.String(length=50), nullable=False, comment="Unique identifier for the team (e.g., 'backend-team')"),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Team name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Team description and focus area'),
    sa.Column('lead_id', sa.UUID(), nullable=True, comment='ID of the team lead'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['agent_desks.id'], name='fk_team_lead', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_created_at'), 'teams', ['created_at'], unique=False)
    op.create_index(op.f('ix_teams_deleted_at'), 'teams', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_team_id'), 'teams', ['team_id'], unique=True)
    op.create_table('workflows',
    sa.Column('workflow_id', sa.String(length=50), nullable=False, comment='Unique identifier for the workflow'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Workflow name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Workflow description'),
    sa.Column('trigger', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Trigger configuration (type, conditions, keywords)'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional workflow configuration'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_created_at'), 'workflows', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflows_deleted_at'), 'workflows', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_workflow_id'), 'workflows', ['workflow_id'], unique=True)
    op.create_table('agent_desks',
    sa.Column('desk_id', sa.String(length=50), nullable=False, comment="Unique identifier for the desk (e.g., 'cto-001')"),
    sa.Column('title', sa.String(length=200), nullable=False, comment="Job title (e.g., 'Chief Technology Officer')"),
    sa.Column('role', sa.Enum('EXECUTIVE', 'MANAGER', 'SENIOR_ENGINEER', 'ENGINEER', 'JUNIOR_ENGINEER', 'QA_ENGINEER', 'SECURITY_ANALYST', 'RESEARCHER', name='agent_role'), nullable=False, comment='Business role of the agent'),
    sa.Column('llm_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='LLM configuration (provider, model, temperature, etc.)'),
    sa.Column('capabilities', sa.ARRAY(sa.String()), nullable=False, comment='List of agent capabilities'),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False, comment='Level in organizational hierarchy (0=top)'),
    sa.Column('status', sa.Enum('ACTIVE', 'IDLE', 'BUSY', 'OFFLINE', name='desk_status'), nullable=False, comment='Current status of the agent desk'),
    sa.Column('memory', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Agent memory (conversation history, learnings, context)'),
    sa.Column('reports_to_id', sa.UUID(), nullable=True, comment='ID of the manager this desk reports to'),
    sa.Column('team_id', sa.UUID(), nullable=True, comment='ID of the team this desk belongs to'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reports_to_id'], ['agent_desks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_desks_created_at'), 'agent_desks', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_desks_deleted_at'), 'agent_desks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agent_desks_desk_id'), 'agent_desks', ['desk_id'], unique=True)
    op.create_index(op.f('ix_agent_desks_id'), 'agent_desks', ['id'], unique=False)
    op.create_index(op.f('ix_agent_desks_role'), 'agent_desks', ['role'], unique=False)
    op.create_index(op.f('ix_agent_desks_status'), 'agent_desks', ['status'], unique=False)
    op.create_index(op.f('ix_agent_desks_team_id'), 'agent_desks', ['team_id'], unique=False)
    op.create_table('committee_members',
    sa.Column('committee_id', sa.UUID(), nullable=False),
    sa.Column('desk_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['desk_id'], ['agent_desks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('committee_id', 'desk_id')
    )
    op.create_table('task_routing_rules',
    sa.Column('rule_id', sa.String(length=50), nullable=False, comment='Unique identifier for the routing rule'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Rule name'),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False, comment='Keywords to match in task title/description'),
    sa.Column('priority_threshold', sa.Integer(), nullable=True, comment='Minimum priority level to trigger this rule (1-4)'),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True, comment='Desk to assign matching tasks to'),
    sa.Column('assigned_role', sa.String(length=100), nullable=True, comment='Role to assign matching tasks to'),
    sa.Column('escalation_desk_id', sa.UUID(), nullable=True, comment='Desk to escalate to if primary assignment fails'),
    sa.Column('notify_committee_id', sa.UUID(), nullable=True, comment='Committee to notify when rule triggers'),
    sa.Column('rule_priority', sa.Integer(), nullable=False, comment='Priority of this rule (higher number = higher priority)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['agent_desks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['escalation_desk_id'], ['agent_desks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notify_committee_id'], ['committees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_routing_rules_created_at'), 'task_routing_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_routing_rules_deleted_at'), 'task_routing_rules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_task_routing_rules_id'), 'task_routing_rules', ['id'], unique=False)
    op.create_index(op.f('ix_task_routing_rules_rule_id'), 'task_routing_rules', ['rule_id'], unique=True)
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=50), nullable=False, comment="Unique identifier for the task (e.g., 'task_0001')"),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Task title'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed task description'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', 'FAILED', 'BLOCKED', name='task_status'), nullable=False, comment='Current status of the task'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'), nullable=False, comment='Task priority level'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='ID of the desk that created this task'),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True, comment='ID of the desk assigned to this task'),
    sa.Column('qa_required', sa.Boolean(), nullable=False, comment='Whether QA review is required'),
    sa.Column('qa_assigned_to_id', sa.UUID(), nullable=True, comment='ID of the desk assigned for QA review'),
    sa.Column('parent_task_id', sa.UUID(), nullable=True, comment='ID of the parent task (if this is a subtask)'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Timestamp when task was completed'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['agent_desks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['agent_desks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qa_assigned_to_id'], ['agent_desks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to_id'), 'tasks', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    op.create_table('workflow_steps',
    sa.Column('step_name', sa.String(length=200), nullable=False, comment='Name of this workflow step'),
    sa.Column('step_order', sa.Integer(), nullable=False, comment='Order of this step in the workflow (0-indexed)'),
    sa.Column('assigned_role', sa.String(length=100), nullable=True, comment="Role assigned to this step (e.g., 'senior_engineer')"),
    sa.Column('assigned_desk_id', sa.UUID(), nullable=True, comment='Specific desk assigned to this step'),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Conditional logic for step execution'),
    sa.Column('timeout_minutes', sa.Integer(), nullable=True, comment='Timeout for this step in minutes'),
    sa.Column('workflow_id', sa.UUID(), nullable=False, comment='ID of the workflow this step belongs to'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_desk_id'], ['agent_desks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_created_at'), 'workflow_steps', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_steps_id'), 'workflow_steps', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_steps_workflow_id'), 'workflow_steps', ['workflow_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.String(length=50), nullable=False, comment='Unique identifier for the artifact'),
    sa.Column('artifact_type', sa.String(length=100), nullable=False, comment='Type of artifact (code, document, analysis, etc.)'),
    sa.Column('content', sa.Text(), nullable=False, comment='The actual content of the artifact'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional metadata about the artifact'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='ID of the task this artifact belongs to'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_artifact_id'), 'artifacts', ['artifact_id'], unique=True)
    op.create_index(op.f('ix_artifacts_artifact_type'), 'artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_artifacts_created_at'), 'artifacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_artifacts_id'), 'artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_artifacts_task_id'), 'artifacts', ['task_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_artifacts_task_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_created_at'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_type'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_workflow_steps_workflow_id'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_id'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_created_at'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_task_routing_rules_rule_id'), table_name='task_routing_rules')
    op.drop_index(op.f('ix_task_routing_rules_id'), table_name='task_routing_rules')
    op.drop_index(op.f('ix_task_routing_rules_deleted_at'), table_name='task_routing_rules')
    op.drop_index(op.f('ix_task_routing_rules_created_at'), table_name='task_routing_rules')
    op.drop_table('task_routing_rules')
    op.drop_table('committee_members')
    op.drop_index(op.f('ix_agent_desks_team_id'), table_name='agent_desks')
    op.drop_index(op.f('ix_agent_desks_status'), table_name='agent_desks')
    op.drop_index(op.f('ix_agent_desks_role'), table_name='agent_desks')
    op.drop_index(op.f('ix_agent_desks_id'), table_name='agent_desks')
    op.drop_index(op.f('ix_agent_desks_desk_id'), table_name='agent_desks')
    op.drop_index(op.f('ix_agent_desks_deleted_at'), table_name='agent_desks')
    op.drop_index(op.f('ix_agent_desks_created_at'), table_name='agent_desks')
    op.drop_table('agent_desks')
    op.drop_index(op.f('ix_workflows_workflow_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_deleted_at'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_created_at'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_teams_team_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_deleted_at'), table_name='teams')
    op.drop_index(op.f('ix_teams_created_at'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_organizations_org_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_notifications_sent'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_metrics_metric_type'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_metric_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_created_at'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_committees_id'), table_name='committees')
    op.drop_index(op.f('ix_committees_deleted_at'), table_name='committees')
    op.drop_index(op.f('ix_committees_created_at'), table_name='committees')
    op.drop_index(op.f('ix_committees_committee_id'), table_name='committees')
    op.drop_table('committees')
    # ### end Alembic commands ###
